name: Metrics
on:
  # Schedule updates (every 24 hours at midnight UTC)
  schedule: [{ cron: "0 0 * * *" }]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: { branches: ["master", "main"] }

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: ðŸ› ï¸ Setup Output Branch
        env:
          GITHUB_TOKEN: ${{ secrets.METRICS_TOKEN }}
        run: |
          git fetch origin
          if ! git ls-remote --exit-code --heads origin metrics-render; then
            echo "Branch metrics-render does not exist. Creating it..."
            git config --global user.name "github-actions[bot]"
            git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git checkout --orphan metrics-render
            git rm -rf .
            git commit --allow-empty -m "chore: initialize metrics branch"
            git push origin metrics-render
            git checkout main
          else
            echo "Branch metrics-render already exists."
          fi

      - name: ðŸ“… IsoCalendar
        uses: lowlighter/metrics@latest
        with:
          filename: metrics-isocalendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          output_action: commit
          committer_branch: metrics-render
          committer_message: "chore: update metrics [skip ci]"
          user: Aayushyaash
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          config_display: large

      - name: ðŸ§© LeetCode
        uses: lowlighter/metrics@latest
        with:
          filename: metrics-leetcode.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          output_action: commit
          committer_branch: metrics-render
          committer_message: "chore: update metrics [skip ci]"
          plugin_leetcode: yes
          plugin_leetcode_user: Aayushyaash
          plugin_leetcode_sections: solved, skills
          config_display: large

      - name: ðŸˆ·ï¸ Languages
        uses: lowlighter/metrics@latest
        with:
          filename: metrics-languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          output_action: commit
          committer_branch: metrics-render
          committer_message: "chore: update metrics [skip ci]"
          user: Aayushyaash
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
            gnuplot
          plugin_languages_indepth: yes
          plugin_languages_details: lines, percentage
          plugin_languages_limit: 8
          plugin_languages_colors: github
          config_display: large
